### ISSUE TITLE
Facebook X-Facebook-Platform SASL Not Working

### ISSUE THREAD

**Issue by eskimooo** [hanzz/libtransport#14]
Cannot use X-Facebook-Platform SASL with `spectrum2_libpurple_backend` nor `spectrum2_swiften_backend`. Authentication is only occuring with DIGEST-MD5. 

We have tried using the spectrum 1 config options to no avail as it does not appear to recognize these:

```
fb_api_key=
fb_api_secret=
```

We are passing the `UserID` after initiating the FB session and passing the `access_token` as the password.

**Comment by vitalyster** [comment]
Facebook deprecate Chat API v1, so it is not relevant anymore
