### ISSUE TITLE
vcard charset and  log-bug

### ISSUE THREAD

**Issue by askovpen** [hanzz/libtransport#3]
407e09ebb0db5d00f4700392d349303b0eaff37a

1 Encoding=windows-1251, backend - purple,icq

messages OK, vcard - wrong:

Received IQ:vCard result from <539539@icq.skovpen.org>
Name: Ñìàêñ
Nickname: SM@x

2 logs

log4cxx = yes. config default.
log messages show in log-files and in stdout

**Comment by vitalyster** [comment]
Reopen if problem still exists
